- hosts: qdocker
  become: true
  pre_tasks:
    - name: Configure DMZ ethernet adapter
      ansible.builtin.template:
        src: roles/docker/templates/99-ens19.yaml.j2
        dest: /etc/netplan/99-ens19.yaml
        owner: root
        group: root
        mode: 0644
    
    - name: Netplan apply
      ansible.builtin.command: 
        cmd: netplan apply
      register: output
      changed_when: output.rc == 0
  
  roles:
    - common
    - mounts
    - docker
    - cron
