- name: Update openssl
  hosts: all
  become: true
  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Print packages
    ansible.builtin.debug:
      msg: "{{ ansible_facts.packages['openssl'] }}"
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: true
    when: ansible_facts['os_family'] == "Debian"
  - name: Update openssl
    ansible.builtin.package:
      name: openssl
      state: latest
    when: "'openssl' in ansible_facts.packages"
