version: '3.3'
services:
    grafana:
        container_name: grafana
        user: root
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_DEFAULT_INSTANCE_NAME=qgrafana
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=mail.lupinelab.co.uk:587
            - GF_SMTP_STARTTLS_POLICY=true
            - GF_SMTP_FROM_ADDRESS=grafana@lupinelab.co.uk
        volumes:
            - '/$HOME/docker/grafana/data:/var/lib/grafana'
        ports:
            - 3000:3000
        restart: unless-stopped
        image: grafana/grafana-oss:latest