- name: Add dockerupdate cron
  ansible.builtin.cron:
    name: dockerupdate
    minute: '0'
    hour: '13'
    weekday: '1'
    user: "{{ lookup('env', 'USERNAME') }}"
    job: '/usr/local/bin/dockerupdate -ia && docker system prune -f --volumes'
  when: lookup('env', 'DOPPLER_ENVIRONMENT') == 'prod'

- name: Add backup cron
  ansible.builtin.cron:
    name: docker backup
    minute: '0'
    hour: '10'
    weekday: '1'
    user: "{{ lookup('env', 'USERNAME') }}"
    job: 'rsync -av /home/jedrw/docker --exclude=influxdb /mnt/Backup/configs/docker --delete'
  when: lookup('env', 'DOPPLER_ENVIRONMENT') == 'prod'
