- name: Install common packages
  ansible.builtin.package:
    name:
      - curl
      - inetutils-traceroute
      - jq
      - nano
      - pip
      - telnet
    state: present

- name: Install pexpect
  ansible.builtin.pip:
    name:
      - pexpect
    break_system_packages: true
    state: present
