- name: Install smb packages
  ansible.builtin.package:
    name: samba
    state: present

- name: Configure smbd
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart smbd

- name: Check smb user exists
  ansible.builtin.command:
    cmd: sudo pdbedit -L
  register: smbd_user_exists
  changed_when: false

- name: Create smb user and set password
  ansible.builtin.shell: "(echo {{ lookup('env', 'SMBPASSWD') }}; echo {{ lookup('env', 'SMBPASSWD') }}) | smbpasswd -a -s {{ lookup('env', 'USERNAME') }}"
  register: smbd_output
  no_log: true
  when: smbd_user_exists.stdout is not match(lookup('env', 'USERNAME'))
  changed_when: smbd_output.rc == 0
  ignore_errors: true
