- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-kernel-server
    state: latest

- name: Configure nfs exportfs
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nfs-server
    - Export nfs shares