- name: Copy kubeconfig create script
  ansible.builtin.copy:
    src: create_kubeconfig
    dest: /root/
    mode: u+x
  become: true
  when: inventory_hostname == "k-c-01"

- name: Make dirs
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/gen/{{ username }}/{{ item }}"
    state: "directory"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
  loop:
    - "keys"
    - "kube"

- name: Kubeconfig exists?
  ansible.builtin.stat:
    path: /var/lib/rancher/k3s/gen/kube/config
  register: kubeconfig_exists

- name: Run generate script
  ansible.builtin.command:
    cmd: "/root/create_kubeconfig"
  when: not kubeconfig_exists.stat.exists
  register: created_kubeconfig
  changed_when: created_kubeconfig.rc == 0

- name: Change owner of kubeconfig
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/gen/{{ username }}/kube/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
