- name: Newaliases
  ansible.builtin.command:
    cmd: newaliases
  register: output
  changed_when: output.rc == 0

- name: Postfix reload
  ansible.builtin.service:
    name: postfix
    state: reloaded
