- name: Generate keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ lookup('env', 'USERNAME') }}/.ssh/id_ed25519"
    type: ed25519
    owner: "{{ lookup('env', 'USERNAME') }}"
  register: keypair

- name: Add public key to backup host
  authorized_key:
    user: "{{ lookup('env', 'USERNAME') }}"
    state: present
    key: "{{ keypair.public_key }}"
  delegate_to: "{{ backup_host }}"
  become: false