version: '3.3'
services:
    influxdb:
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - /$HOME/docker/influxdb/data:/var/lib/influxdb2
            - /$HOME/docker/influxdb/config:/etc/influxdb2
        restart: unless-stopped
        image: influxdb:latest