- name: Enable iommu
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!iommu=pt).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 iommu=pt"'
    backup: true
    backrefs: true
  notify:
    - Update grub
    - Reboot
