- name: Create container folder
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USERNAME') }}/docker-containers/{{ item }}"
    state: directory
    owner: "{{ lookup('env', 'USERNAME') }}"
    group: "{{ lookup('env', 'USERNAME') }}"
    mode: "0770"
  become: false
  loop: "{{ containers }}"

- name: Copy docker-compose file
  ansible.builtin.copy:
    src: "{{ item }}.yml"
    dest: "/home/{{ lookup('env', 'USERNAME') }}/docker-containers/{{ item }}/docker-compose.yml"
    mode: "0660"
  become: false
  loop: "{{ containers }}"

- name: Create and start container
  community.docker.docker_compose_v2:
    project_src: "/home/{{ lookup('env', 'USERNAME') }}/docker-containers/{{ item }}"
    pull: always
  become: false
  loop: "{{ containers }}"
