- name: Get latest release info for dockerupdate
  ansible.builtin.uri:
    url: https://api.github.com/repos/lupinelab/dockerupdate/releases/latest
    return_content: true
  register: docker_latest_release

- name: Make a workdir
  ansible.builtin.file:
    path: /tmp/dockerupdate
    state: directory
    mode: "0700"

- name: Download dockerupdate
  ansible.builtin.get_url:
    url: "{{ docker_latest_release.json.assets[0].browser_download_url }}"
    dest: /tmp/dockerupdate/dockerupdate.tar.gz
    mode: "0700"

- name: Un-archive dockerupdate
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/dockerupdate/dockerupdate.tar.gz
    dest: /tmp/dockerupdate

- name: Install dockerupdate
  ansible.builtin.copy:
    src: /tmp/dockerupdate/dockerupdate
    remote_src: true
    dest: /usr/local/bin/dockerupdate
    mode: "0755"

- name: Remove workdir
  ansible.builtin.file:
    path: "/tmp/{{ lookup('env', 'USERNAME') }}/dockerupdate"
    state: absent
