- name: Install docker
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USERNAME') }}"
    groups: docker
    append: true

- name: Reset ssh connection to allow user/group changes to take effect
  ansible.builtin.meta: reset_connection

- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKERHUB_PASSWD') }}"
    validate_certs: true
  no_log: true
  become: false

- name: Log into lupinelab registry
  community.docker.docker_login:
    registry_url: "{{ lookup('env', 'REGISTRY_URL') }}"
    username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
    password: "{{ lookup('env', 'REGISTRY_PASSWD') }}"
    validate_certs: true
  no_log: true
  become: false

- name: Install dockerupdate
  ansible.builtin.include_tasks:
    file: "dockerupdate.yaml"

- name: Deploy containers
  ansible.builtin.include_tasks:
    file: "containers.yaml"
  when: >
    inventory_hostname == "qdocker"

  # lookup('env', 'DOPPLER_ENVIRONMENT') == 'prod'
  # and inventory_hostname == "qdocker"
