- name: Provision base image
  hosts: default
  become: true
  pre_tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: latest
    - name: Enable qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
  roles:
    - common
  post_tasks:
    - name: Reset machine-id
      ansible.builtin.shell:
        cmd: |
          echo -n >/etc/machine-id
          rm /var/lib/dbus/machine-id
          ln -s /etc/machine-id /var/lib/dbus/machine-id
      register: output
      changed_when: output.rc == 0
