- name: Provision kproximate template
  hosts: default
  become: true
  pre_tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present
    - name: Enable qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
  roles:
    - common
    - user
  post_tasks:
    - name: Permanently disable swap
      ansible.posix.mount:
        src: /swap.img
        path: none
        state: absent_from_fstab
    - name: Install k3s required packages
      ansible.builtin.package:
        name:
          - runc
          - containerd
          - nfs-common
        state: present
    - name: Reset machine-id
      ansible.builtin.shell:
        cmd: |
          rm -rf /var/lib/cloud/*
          echo -n > /etc/machine-id
          rm /var/lib/dbus/machine-id
          ln -s /etc/machine-id /var/lib/dbus/machine-id
      register: output
      changed_when: output.rc == 0
