- name: Build/Configure tshare
  hosts: tshare
  become: true
  vars_files:
    - roles/rclone/vars/main.yaml
  roles:
    - mounts
    - smbd
    - nfs
    - stefangweichinger.ansible_rclone
    - cron
